export const LOGIN="LOGIN"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const LOGOUT="LOGOUT"
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const EDIT_USER="EDIT_USER"
export const EDIT_SUCCESS="EDIT_SUCCESS"
export const EDIT_FAILURE="EDIT_FAILURE"
export const CANCEL_EDIT="CANCEL_EDIT"

export const DELETE_USER="DELETE_USER"
export const DELETE_SUCCESS="DELETE_SUCCESS"
export const DELETE_FAILURE="DELETE_FAILURE"

export const ADD_USER="ADD_USER"
export const ADD_SUCCESS="ADD_SUCCESS"
export const ADD_FAILURE="ADD_FAILURE"

export const FETCH_USERS="FETCH_USERS"
